### ISSUE TITLE
Incentivise accepting cookies by blocking all app access

### ISSUE THREAD

**Issue by TadeSF** [DeutscheModelUnitedNations/munify-chase#183]
Possibly with a backdrop-blur mask over everything but the cookie consent banner, so that it gets overly obvious that you need to accept

**Comment by ahsanfarooq210** [comment]
Hi @TadeSF. I would like to work on this issue

**Comment by TadeSF** [comment]
Awesome! It's all yours :)

**Comment by ahsanfarooq210** [comment]
Hi @TadeSF. Please review the PR
