### ISSUE TITLE
Omit (finally) manual conference creation

### ISSUE THREAD

**Issue by TadeSF** [DeutscheModelUnitedNations/munify-chase#196]
We need to omit the plus at the home screen and the corresponding page to create conferences

**Comment by ahsanfarooq210** [comment]
Hi @TadeSF. I want to work on this issue

**Comment by TadeSF** [comment]
Hey @ahsanfarooq210, sure, go ahaed!

I was referring to this whole folder which can be safely deleted since it has no functionality at the moment: chase/frontend/app/app/admin/(start)

And you can find and remove the Plus-Button in this component:
chase/frontend/components/home/navbar.tsx

You might not see the button in your local development, since it is only an Icon that you can't render atm without FontAwesome Pro Icons. But you can take a look at [this website](https://chase.dmun.de) to see the button in action, which should be removed.

Do you have any more questions?

![CleanShot 2024-06-04 at 16 10 41@2x](https://github.com/DeutscheModelUnitedNations/munify/assets/42637916/961d8671-0cd5-424b-baf7-71e1a115a79d)

P.S. @m1212e do you have something to add / objections to deleting the pages? I don't think we have already talked about this in detail.

**Comment by m1212e** [comment]
No we should take it out until we got the actual functionality to back that up!

**Comment by ahsanfarooq210** [comment]
Hi @TadeSF .I had a few deadlines to finish my job on an urgent priority. This issue will be resolved within this week.

**Comment by ahsanfarooq210** [comment]
Hi @TadeSF Please review the PR

**Comment by m1212e** [comment]
No worries, you can work on this whenever you want, it's your free time! Thanks for the contribution. We currently do a big rework on some project structures and will postpone this during this period. We will take care of this as soon as possible!
