### ISSUE TITLE
Password reset error while resetting to same Password

### ISSUE THREAD

**Issue by maximilianilzhoefer** [DeutscheModelUnitedNations/munify-chase#197]
If I try to reset my password to the same password i get a internal Server issue.

**Comment by ahsanfarooq210** [comment]
Hi @TadeSF. I want to work on this issue

**Comment by TadeSF** [comment]
Hey @ahsanfarooq210! Awesome, thank you! Please go ahaed ;)

**Comment by ahsanfarooq210** [comment]
Hi @TadeSF. While resetting the password, we are explicitly throwing an error if the previous and current passwords are the same. What should the API behavior be in this case?

**Comment by ahsanfarooq210** [comment]
ooh got it. Well, in that case, we should close this ticket
